### ISSUE TITLE
General- 5.10 is detected as possible malware by Windows Defender

### ISSUE THREAD

**Issue by fudgepop01** [vitor251093/KHMelonMix#362]
**Describe the bug**
I am unable to download version 5.10 because Windows Defender automatically flags it as malware and removes it immediaely

**To Reproduce**
1. Windows 11
2. click on "MelonMix-windows-x86_64.zip" in the releases page
3. witness antivirus flag things

**Expected behavior**
I expect to be able to download the emulator without my antivirus flagging it

**Desktop (please complete the following information):**
 - **Game:** emulator
 - **OS:** Windows 15.10
 - **Melon Mix Version:** e

**Comment by vitor251093** [comment]
The only thing that changed since 0.5.9 that could cause something like is the Windows build workflow

Can you confirm if the same issue also happens if you download the latest melonDS (not Melon Mix) Actions build?

**Comment by Hackche** [comment]
I got flagged too, on Windows 10. Kinda concerning af, I'd check the actions build but frankly I'm a normie when it comes to github as a site... On the actions tab under melonDS I don't see an explicit download link so 🤷‍♂️
I hope this is solved soon tho?

**Comment by vitor251093** [comment]
> On the actions tab under melonDS I don't see an explicit download link so 🤷‍♂️
You need to open the latest Windows build on the list, scroll down, and you will find the link. It doesn't look like a link (thanks GitHub...) but it is

**Comment by IcyWind14** [comment]
I'm also having 0.5.10 get detected as "Trojan:Script/Wacatac.B!ml" by Windows Defender. I've tried downloading some of melonDS's latest action releases and none of them are flagged. The problem is exclusive to Melon Mix.

**Comment by sandwichwater** [comment]
to be fair , it was something that wasnt ever merged into melonds , and it was from 10 months ago as well so any action builds that would have had it are long expired by now . considering the false positives only started when we merged it , its still not off the table that it is what caused the false positive

**Comment by vitor251093** [comment]
The change I'm referring to is actually from last week though 
https://github.com/melonDS-emu/melonDS/commit/9ed7e5803e55c5eeb29ec560c8659b38ed331749

Can someone confirm if the Melon Mix latest Actions builds are still affected by this or if it was an one time thing?

**Comment by IcyWind14** [comment]
Downloading all of the latest Action builds for Melon Mix, only [Merge pull request #360 from melonDS-emu/master](https://github.com/vitor251093/KHMelonMix/actions/runs/14482644082) is being detected as malware. Every single build after it is coming up clean. It does seem to have been a one time issue.

**Comment by vitor251093** [comment]
Well, I guess we can consider it fixed for 0.6.0 then
